### ISSUE TITLE
AttributeError: 'llist.dllist' object has no attribute 'iternodes'

### ISSUE THREAD

**Issue by SegundoBob** [rgsoda/pypy-llist#7]
The documentation says that an llist.dllist object has a method iternodes() [dllist object](https://pythonhosted.org/pyllist/#dllist-objects):
```
iternodes([to])

    Iterate over the list starting from the first node. If to is specified, iteration stops when the current node becomes equal to argument to.
```
### Version
```
Successfully installed llist-0.5
```

**Comment by ajakubek** [comment]
The llist-0.5 module that you installed is a different project - https://github.com/ajakubek/python-llist.
You can find its documentation at https://pythonhosted.org/llist/
It doesn't support the iternodes method yet.

However, we try to maintain compatible APIs between python-llist (which is a native C module) and pypy-llist (pure Python implementation), so I created a corresponding ticket in the other project (https://github.com/ajakubek/python-llist/issues/5).

I'm going to close this issue, since nothing needs to be done in pypy-llist.

**Comment by SegundoBob** [comment]
Thank you.
SegundoBob
